# Generated by Django 4.2.2 on 2023-11-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='', max_length=20)),
                ('product_name', models.CharField(default='', max_length=20)),
                ('unit_id', models.IntegerField(default='', max_length=20)),
                ('amount', models.FloatField(default='', max_length=20)),
                ('status_id', models.IntegerField(default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.IntegerField(default='', max_length=20)),
                ('unit_name', models.CharField(default='', max_length=225)),
            ],
        ),
    ]
