# Generated by Django 4.2.2 on 2023-11-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='status_id',
            field=models.IntegerField(default='0', max_length=20, null=True),
        ),
    ]
