# Generated by Django 4.2.2 on 2023-11-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='product_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
