# Generated by Django 4.2.2 on 2023-11-10 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_alter_details_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='product_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='details',
            name='product_name',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='details',
            name='status_id',
            field=models.IntegerField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='unit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_home.unit'),
        ),
    ]
