# Generated by Django 4.2.2 on 2023-11-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_details_product_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='product_code',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='details',
            name='unit_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='details',
            name='status_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
