# Generated by Django 4.2.2 on 2023-11-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0003_rename_product_code_details_amount_details_status_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(default='', max_length=20)),
                ('unit_name', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
