# Generated by Django 4.2.2 on 2023-11-10 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0003_alter_details_product_id_alter_details_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='unit_id',
            new_name='unit',
        ),
    ]
