# Generated by Django 4.2.2 on 2023-11-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0004_rename_unit_id_details_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='product_id',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
