# Generated by Django 4.2.2 on 2023-11-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0004_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_id',
            field=models.IntegerField(default='', max_length=20),
        ),
    ]
