# Generated by Django 4.2.2 on 2023-11-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0005_alter_unit_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(default='', max_length=225),
        ),
    ]
