# Generated by Django 4.2.2 on 2023-11-13 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0005_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='borrow_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField(null=True)),
                ('b_amount', models.FloatField(default='', max_length=20)),
                ('bproduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_home.details')),
            ],
        ),
        migrations.DeleteModel(
            name='member',
        ),
    ]
