# Generated by Django 4.2.2 on 2023-11-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0006_alter_unit_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='status_id',
            field=models.IntegerField(default='', max_length=20),
        ),
    ]
