# Generated by Django 4.2.7 on 2023-11-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0007_alter_details_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='amount',
            field=models.FloatField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='details',
            name='unit_id',
            field=models.IntegerField(default='', max_length=20),
        ),
    ]
